### ISSUE TITLE
Add support for Python 3.10

### ISSUE THREAD

**Issue by randomir** [recruit-communications/pyqubo#116]
We are adding support for Python 3.10 to [D-Wave Ocean SDK](https://github.com/dwavesystems/dwave-ocean-sdk/), so we need `pyqubo` (as our dependency) to support Python 3.10 as well.

Blocked by #90.

**Comment by kotarotanahashi** [comment]
Thank you for reporting!
It was resolve by https://github.com/recruit-communications/pyqubo/releases/tag/1.2.0
