### ISSUE TITLE
Use an optimized simulated annealing, instead of the reference implementation in dimod

### ISSUE THREAD

**Issue by randomir** [recruit-communications/pyqubo#19]
In `pyqubo.utils` module, a reference implementation of simulated annealing is used (`dimod.reference.SimulatedAnnealingSampler`), instead of the optimized one available in [`dwave-neal`](https://github.com/dwavesystems/dwave-neal) (`neal.SimulatedAnnealingSampler`).

Details here: https://github.com/dwavesystems/dimod/issues/298.

**Comment by kotarotanahashi** [comment]
resolved in #24
