### ISSUE TITLE
PyPi version behind?

### ISSUE THREAD

**Issue by jberwald** [recruit-communications/pyqubo#31]
The version of PyQubo that installs from PyPi appears to be one minor version behind the master branch in the repo. The reason I think this is because the version that gets installed using `pip install pyqubo` does not appear to include the small change made to `decode_dimod_response`. This means that users requiring this change need install the package directly from master branch on git. 
Thanks!

**Comment by kotarotanahashi** [comment]
@jberwald Thank you for letting me know that. I deployed the latest master to PyPi server.

**Comment by jberwald** [comment]
Thanks for your quick response.
