### ISSUE TITLE
Amazon Braketでの利用

### ISSUE THREAD

**Issue by Ooshita** [recruit-communications/pyqubo#80]
PyQUBOでQUBOを作成し、Amazon Braketでアニーリングを行いたいです。

Array.createメソッドで配列を作成し、Braketでアニーリングをしようとするとエラーになります。

以下の構造ではなく
{('[30][21]', '[30][21]'): -5.0,
 ('[81][15]', '[81][15]'): -5.0,
 ('[9][26]', '[9][26]'): -5.0,

次のようにタプルになっていないといけないようです。
{((30, 21), (30, 21)): -5.0,
 ((81,15), (81, 15)): -5.0,
 ((9,26), (9,26)): -5.0,

お忙しいとは思いますが、対応していただけますと大変助かります。

**Comment by kotarotanahashi** [comment]
@Ooshita ご質問ありがとうございます。QUBOのインデックスを整数値のタプルで出力するには、to_quboメソッドでindex_labelという引数をTrueに指定することで実現できます。
もとのラベルと整数値の対応関係は、modelオブジェクトのvariablesというメンバ変数に格納されております。

```
>>> from pyqubo import Binary
>>> x, y, z = Binary("x"), Binary("y"), Binary("z")
>>> model = (x*y + y*z + 3*z).compile()
>>>model.to_qubo()
({('x', 'x'): 0.0,
('x', 'y'): 1.0,
('y', 'y'): 0.0,
('z', 'y'): 1.0,
('z', 'z'): 3.0},
0.0)
>>> model.to_qubo(index_label=True) # 整数値を出力する場合は、index_labelをTrueに設定してください。
({(0, 0): 3.0, (0, 2): 1.0, (1, 1): 0.0, (1, 2): 1.0, (2, 2): 0.0}, 0.0)
>>> model.variables # もとの文字列ラベルと整数値の対応は、variablesを見えるとわかります。
['z', 'x', 'y']
```

詳しくはhttps://pyqubo.readthedocs.io/en/latest/reference/model.html#pyqubo.to_qubo をご覧ください。

**Comment by Ooshita** [comment]
@kotarotanahashi ご回答ありがとうございます！詳しく教えていただき感謝いたします！
